url: https://raketanalunu.github.io/frontend
title: Evgenia frontend developer
encoding: UTF-8

baseurl: "https://raketanalunu.github.io/frontend"

description: "My personal website. Enjoy!"


# Build settings
markdown: kramdown


# Content
vk: "https://vk.com/raketanalunu"
instagram: "https://www.instagram.com/raketanalunu/" 